Models/ErrorViewModel.cs
namespace practica4.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Opinion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace practica4.Models
{
    [Table("t_opiniones")]
    public class Opinion
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Nombres son obligatorios.")]
        public string? Nombres { get; set; }
        [NotNull]
        public string? Email { get; set; }
        [NotNull]
        public string? Mensaje { get; set; }

        public string? Etiqueta { get; set; }

        public float Puntuacion { get; set; }



    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using practica4.Models;

namespace practica4.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OpinionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using practica4.Data;
using practica4.ML;
using practica4.Models;

namespace practica4.Controllers
{
   
    public class OpinionController : Controller
    {
        private readonly ILogger<OpinionController> _logger;
        private readonly ApplicationDbContext _context;

        public OpinionController(ILogger<OpinionController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registrar(Opinion opinion)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Load sample data
                    var sampleData = new MLModel1.ModelInput()
                    {
                        Col1 = opinion.Mensaje,
                         // No es necesario, pero lo dejamos como placeholder
                    };

                    //Load model and predict output
                    var result = MLModel1.Predict(sampleData);
                    var predictedLabel = result.PredictedLabel;
                    var scorePositive = result.Score[1];
                    var scoreNegative = result.Score[0];

                    //Check if the result is positive or negative
                    if (predictedLabel == 1)
                    {
                        opinion.Etiqueta = "Positivo";
                        opinion.Puntuacion = scorePositive;
                    }
                    else
                    {
                        opinion.Etiqueta = "Negativo";
                        opinion.Puntuacion = scoreNegative;
                    }

                    _context.DbSetOpinion.Add(opinion);
                    _context.SaveChanges();
                    _logger.LogInformation("Se envio la opinion");
                    ViewData["Message"] = "Se envio la opinion";
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error al registrar la opinion");
                    ViewData["Message"] = "Error al registrar la opinion: " + ex.Message;
                }
            }
            else
            {
                ViewData["Message"] = "Datos de entrada no válidos";
            }
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Opinion/Index.cshtml
@model practica4.Models.Opinion


@{
    ViewBag.Title = "Contacto";
}

<h1>Deja tu opinion</h1>

<form method="post" asp-action="Registrar">
    <div class="form-group">
        <label asp-for="Nombres" class="control-label"></label>
        <input asp-for="Nombres" class="form-control" />
        <span asp-validation-for="Nombres" class="text-danger"></span>
    </div>
    <div class="form-group  mt-2">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group  mt-2">
        <label asp-for="Mensaje" class="control-label"></label>
        <textarea asp-for="Mensaje" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Mensaje" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Enviar</button>
</form>
<h1>@ViewData["Message"]</h1>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - practica4</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/practica4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">practica4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Opinion" asp-action="Index">Opiniones</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - practica4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>